# Nettoyage ficher json scrapping

######

In [ ]:
import json
import re
with open('test.json', 'r') as f:
    data = json.load(f)

print(data[0:5])

In [ ]:
# suppressoin des espaces avant 'cl'
liste_json = []
for rum in data:
    for k, v in rum.items():
        v = v.replace(' cl', 'cl')
        liste_json.append(v)
# liste_json

In [ ]:
for e in liste_json:
    pays = e.split()[-1]

print(e)
print(pays)
# exporter les données dans un fichier json

In [ ]:
import re
listep=[]
for mot in marques:
    mot = re.sub('Rhum|Liqueur|Punch', '', mot)
    listep.append(mot)
print(len(listep))
print(listep)

In [ ]:
# test expression reguliere pour volume
import re

pattern = re.compile(r'\d\dcl')

matches = pattern.findall('efefe 70cl dzef')

for match in matches:
    print(match)

In [ ]:
# s'assurer de la longueur des listes
# regex recherche nom
[a-zA-Zèé]+ [a-zA-Zèé]+ Rhum|[a-zA-Zèé]+ Rhum
[a-zA-Zèé]+ [a-zA-Zèé0-9']+ Rhum|[a-zA-Zèé']+[ ]? Rhum|[a-zA-Zèé']+ Liqueur|[a-zA-Zèé]+ Punch

In [ ]:
import pandas as pd
import json

df = pd.read_json('test.json')
df.head()

In [ ]:
# test expression reguliere pour degre
import re

pattern = re.compile(r'(\d+(?:\.\d+)?°)')

matches = pattern.findall('efefe 50° dzef 55.8°')

for match in matches:
    print(match)

In [ ]:
import pandas as pd

volumes = []
producteurs = []
textes = ['X', '1', '2']
for texte in textes:
    volume = ''
    producteur = ''
    if texte != 'X':
        volume = texte
    else:
        producteur = texte
    volumes.append(volume)
    producteurs.append(producteur)

    
df = pd.DataFrame()
df['volume']  = volumes
df['producteur']  = producteurs
df

In [ ]:
import re

for nom in liste_json:
    pays = nom.split()[-1]
    degre_pattern = re.compile(r'\d\d°|\d\d,\d\d?°')
    degre = degre_pattern.findall(nom)
    volume_pattern = re.compile(r'\d?\dcl|\dL')
    volume = volume_pattern.findall(nom)
    nom1 = re.sub(f'{pays}', '', nom)
    nom2 = re.sub(re.compile(r'\d?\dcl|\dL'), '', nom1)
    nom3 = re.sub(re.compile(r'\d\d°|\d\d,\d\d?°'), '', nom2)
    print(nom3)
    print(pays)
    print(volume)
    print(degre)

######

- Nettoyage des données version prod

In [1]:
from collections import defaultdict
import pandas as pd
import re
import json

origines = []
degres = []
volumes = []
noms = []
producteurs = []
marques = []
liste_json = []

with open('test.json', 'r') as f:
    data = json.load(f)

for rum in data:
    for k, v in rum.items():
        v = v.replace(' cl', 'cl')
        liste_json.append(v)
        
for element in liste_json:
    
    # Origines
    pays = element.split()[-1]
    origines.append(pays)
    if pays:
        element = element.replace(pays, "")
        
    # Producteurs  
    marque_pattern = re.compile(r"[a-zA-Zèé]+[&? [a-zA-Zèé0-9']+ Rhum|[a-zA-Zèé']+[ ]? Rhum|[a-zA-Zèé']+ [Liqueur|Punch|Coffret]+")
    marque = marque_pattern.findall(element)
#     marque = marque.replace("Rhum", "")
    if marque:
        marques.append(marque[0])
    else:
        marques.append("XXXXXXXX")

    # Degres    
    degre_pattern = re.compile(r'\d\d°|\d\d,\d\d?°|\d\d\.\d\d?°')
    degre = degre_pattern.findall(element)
    if degre:
        element = element.replace(degre[0], "")
        degres.append(degre[0])
    else:
        degres.append("")
        
    # Volumes
    volume_pattern = re.compile(r'\d?\dcl|\dL')
    volume = volume_pattern.findall(element)
    if volume:
        element = element.replace(volume[0], "")
        volumes.append(volume[0])
    else:
        volumes.append('')
        
    # Noms rhums    
    noms.append(element) 

# nettoyage Producteurs   
for producteur in marques:
    producteur = re.sub('Rhum|Liqueur|Punch|Coffret', '', producteur)
    producteurs.append(producteur)

In [2]:
# import pandas as pd

# json_tuples = list(zip(noms, producteurs, origines, volumes, degres))
# df = pd.DataFrame(json_tuples)
# df.head(80)

In [3]:
import pandas as pd

df1 = pd.DataFrame()
df1['noms'] = noms
df1['producteurs'] = producteurs
df1['origines'] = origines
df1['volumes'] = volumes
df1['degres'] = degres
df1.head(80)

,noms,producteurs,origines,volumes,degres
0,Longueteau Punch Shrubb,Longueteau,Guadeloupe,1L,25°
1,Montebello Rhum Vieux 6 ans Zenga étui,Montebello,Guadeloupe,,46°
2,Montebello Rhum Blanc Zenga étui,Montebello,Guadeloupe,,60°
3,Karukera Rhum Vieux 2006 Fût 65 70 ans Anniver...,Karukera,Guadeloupe,,"48,30°"
4,Bologne Rhum Blanc Bio,Bologne,Guadeloupe,,45°
...,...,...,...,...,...
75,L'Esprit Rhum Vieux Clarendon 2004,L'Esprit,Jamaïque,,"66,4°"
76,Black Tot Rhum Vieux Fines Caribbean,Black Tot,"46,2°",,
77,Famille Ricci Rhum Vieux Influence 2 étui Aus...,Famille Ricci,Jamaique,,46°
78,Famille Ricci Rhum Vieux Influence 1 étui Tri...,Famille Ricci,Jamaique,,46°
79,Plantation Rhum Vieux 2003 étui,Plantation,Jamaïque,70cl,"49,5°"

In [4]:
df1.to_csv('test_json_new.csv', index = False, header=True)

In [5]:
df1 = pd.read_csv('test_json_new.csv')

In [6]:
df1['producteurs'] = df1['producteurs'].replace('XXXXXXXX', 'Bumbu') 
df1['producteurs'] = df1['producteurs'].replace('JM', 'Rhum JM') 
df1['producteurs'] = df1['producteurs'].replace('James C', 'Saint James') 
df1['producteurs'] = df1['producteurs'].replace('Depaz Doré', 'Depaz') 
df1['producteurs'] = df1['producteurs'].replace('pour rhu', 'Quai Sud') 
df1['producteurs'] = df1['producteurs'].replace(['Maison L', 'Maison La Mauny'], 'La Mauny') 
df1['origines'] = df1['origines'].replace('70cl', 'Guadeloupe') 
df1.loc[df1['producteurs'] == 'Maison La Mauny', 'producteurs'] = 'La Mauny'
df1.loc[df1['producteurs'] == 'Depaz Doré', 'producteurs'] = 'Depaz'
df1.head(241)

,noms,producteurs,origines,volumes,degres
0,Longueteau Punch Shrubb,Longueteau,Guadeloupe,1L,25°
1,Montebello Rhum Vieux 6 ans Zenga étui,Montebello,Guadeloupe,NaN,46°
2,Montebello Rhum Blanc Zenga étui,Montebello,Guadeloupe,NaN,60°
3,Karukera Rhum Vieux 2006 Fût 65 70 ans Anniver...,Karukera,Guadeloupe,NaN,"48,30°"
4,Bologne Rhum Blanc Bio,Bologne,Guadeloupe,NaN,45°
...,...,...,...,...,...
236,Smith & Cross Rhum Vieux Navy Strentgh,Smith & Cross,Jamaïque,70cl,57°
237,Worthy Park Rhum Blanc Rum Bar White Overproof,Worthy Park,Jamaïque,70cl,63°
238,Worthy Park Rhum Vieux Gold,Worthy Park,Jamaïque,1L,40°
239,Wray & Nephew Rhum Blanc Overproof Rum,Wray & Nephew,Jamaïque,70cl,63°
240,Quai Sud mélange pour rhum arrangé Jamaïque 20...,Quai Sud,cocktail,NaN,NaN

In [7]:
df1.to_csv('test_json_work.csv', index = False, header=True)

In [37]:
df1 = pd.read_csv('test_json_work.csv')

In [38]:
dico = {}
liste_car = ['XXXXXXXX', 'JM', 'Depaz Doré', 'Maison La Mauny', 'Maison L', '\'', 
             'de Cori', 'Longueteau  Vieux Cuvée Confrérie du','Bielle  Vieux Millésime 2009 Cuvée Confrérie du', 
             'Discovery', 'Ambré Brun', 'Crème de', 'Favorite  Vieux coeur de', 'VSOP', '4 tubes de', 'Blanc de', 
             'Latitudes', 'pour rhu', 'James C', 'Depaz Doré', 'Blanc Ice', 'Favorite  Vieux Coeur de',
             'Favorite', 'Bally','é','è']
liste_remp = ['Bumbu', 'Rhum JM', 'Depaz', 'La Mauny', 'La Mauny', '', 
              'Saveur de Coriandre', 'Confrérie du Rhum','Confrérie du Rhum', 'Rhum', '', 
              '', 'Favorite', '', '', '', 'Grand Fond Gallion', 'Quai Sud', 'Saint James', 'Depaz', '',
              'La Favorite', 'La Favorite', 'J. Bally','e', 'e']
# création du dictionnaire avec une compréhension de dictionnaire
dico = {k: v for k, v in zip(liste_car, liste_remp)}

In [44]:
dico2 = {}
liste_car = ['Galante', '46,2°', 'Trinidad', '20cl', 'cocktail', 'ï']
liste_remp = ['Marie Galante', 'Ecosse', 'Trinite et Tobago', 'Martinique', 'France', 'i']
# création du dictionnaire avec une compréhension de dictionnaire
dico2 = {k: v for k, v in zip(liste_car, liste_remp)}

In [45]:
import pandas as pd
# il faut que regex=True 
df1.replace({'producteurs': dico}, regex=True,inplace=True)

In [46]:
df1.replace({'origines': dico2}, regex=True,inplace=True)

In [47]:
df1.to_csv('test_json_final.csv', index = False, header=True)

- insertion origine

In [48]:
import csv
# je crée une liste regroupant ma liste de pays
liste_pays = []
with open('test_json_final.csv', newline='', encoding='utf-8') as csvfile:
    test_json = csv.reader(csvfile, delimiter=',')
    for row in test_json:
        # gestion des doublons
        if row[2] not in liste_pays:
            liste_pays.append(row[2])
liste_pays = liste_pays[1:]
print(liste_pays)

['Guadeloupe', 'Marie Marie Galante', 'Barbade', 'Caraibes', 'Martinique', 'Jamaique', 'Ecosse', 'Trinite et Tobago', 'Françaises', 'Guyana', 'france']

In [49]:
import pandas as pd
import re
import psycopg2
import os

conn = psycopg2.connect(
        user = "postgres",
        password = os.environ.get("pg_psw"),
        host = "localhost",
        port = "5432",
        database = "collection4"
)
cur = conn.cursor()
for nom in liste_pays:
    pays = nom.split()[-1]
    cur.execute("SELECT origine.nom FROM origine WHERE origine.nom = (%s) ", (pays,))
    verif = cur.fetchone()
    if not verif:
        cur.execute("INSERT INTO origine (nom) VALUES(%s)", (pays,))
cur.close()
conn.commit()
conn.close()

- insertion producteur

In [ ]:
import psycopg2
import os


conn = psycopg2.connect(
        user = "postgres",
        password = os.environ.get("pg_psw"),
        host = "localhost",
        port = "5432",
        database = "collection4"
)
cur = conn.cursor()

cur.execute(f"""SELECT producteur.nom 
        FROM producteur;
        """)
marque = cur.fetchall()
print(marque[2:4])
# print(marque[0:10])
for e in liste_json:
    for pro[0] in marque:        
        if e.find(pro[0]) == 1:
            print('ok')

In [ ]:
# prod
# fonction d'insertion dans la table producteur
conn = psycopg2.connect(
        user = "postgres",
        password = os.environ.get("pg_psw"),
        host = "localhost",
        port = "5432",
        database = "collection4"
)
cur = conn.cursor()
for producteur, pays in liste_co:
    #print(producteur)
    #print(pays)
    cur.execute(f"""SELECT origine.code_origine 
        FROM origine
        WHERE origine.nom = '{pays}';
        """)
    
    origine = cur.fetchone()[0]
    #print(origine)
    #pays = str(pro[0])
    #print(pays)

    cur.execute(f"INSERT INTO producteur (nom, code_origine) VALUES ('{producteur}', {origine})")
    
cur.close()
conn.commit()
conn.close()